### ISSUE TITLE
Clusters as an SPOF issue

### ISSUE THREAD

**Issue by faddat** [tendermint/mintnet-kubernetes#2]
Just want to say to people that this should probably be used only for very tightly-defined chain operated by a single stakeholder, because the cluster would seem to become the "snapping point."  Lose the cluster, lose the chain.  

Also, lose the parts of the cluster that let the inside talk to the outside, lose the chain as well.  

This said, I think the people who might use this are generally aware of that, but just in case, I'm throwing this issue up here, as it's my opinion that downtime makes any blockchain look quite questionable.  Tendermint would probably recover from such downtime uniquely well, but this downtime would kill ya.  But for prototyping, hells yes to this! 

:) :+1: 

I also wanted to point out that if you're looking to do clusters, using docker's IPVS solution for load balancing would be preferable to this, unless you want your chain to be geographically small / low-node-count.  

These are just thoughts and should not be construed as actual criticism of this thingey, which will speed my testing a great deal.

**Comment by melekes** [comment]
Thank you for your thoughts! They are very much welcome :)

> Lose the cluster, lose the chain.

You are right of course. I'll add the comment to the top of the README. Due to the nature of Kubernetes, where you have a single master/API server, who controls `kubectl` controls the whole cluster. So if the administrator (our user) get hacked, he will loose the chain.

> Also, lose the parts of the cluster that let the inside talk to the outside, lose the chain as well.

It may be completely prohibited on worker nodes (but not on the master/API server).

Also, there is [federation deployment](https://kubernetes.io/docs/user-guide/federation/deployment/), where you can setup multiple clusters in multiple zones.

The security is important here, yes. I'll update README once I wrap my head around this. For now, I've just read a few articles:

- https://kubernetes.io/docs/admin/accessing-the-api/
- http://blog.kubernetes.io/2016/08/security-best-practices-kubernetes-deployment.html
- https://blog.openshift.com/securing-kubernetes/

**Comment by faddat** [comment]
My opinion in this matter is that the best way to address this is not using
kube for now as all of the nodes will be behind kubes strange ingress
system.
